### ISSUE TITLE
"aria-selected" bug in examples/dialog-modal/datepicker-dialog.html

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#1072]
I tried to find a quick fix for this bug but I get lead down a rabbit hole. To see the bug:

1. Type a date in the input text box that is the first of any month (such as "1/1/2019")
2. Tab over to the "choose date" button and open it
3. The first date looks highlighted, but "aria-selected" is not set.

This only happens if you manually add a date that is the first of the month. Any other day works. When trying to fix the code I noticed to things that could be changed to make this example's code much easier to read and edit in the future:

1. The date of month is saved as a zero-indexed value in the DatePicker object (`examples/dialog-modal/js/datepicker.js`). This means, when you make a new date object via `new Date(year, month, day)` using that zero-indexed date, you will actually get the day before the day you wanted. In this date object construction, `day` is expected to be 1-indexed, not 0-indexed (this is confused because month is 0-indexed). Through out the code, some times day is expected to be 1-index and sometimes 0-indexed, and there are many +1 and -1 through out the code because of it. This led in one case to the `aria-selected` bug above.

2. There is a lot of date math that is quite complicated in the same javascript file  (`examples/dialog-modal/js/datepicker.js`). All this math can be handled by the Date object. For example, if you want to subtract 7 days from today:

```
let d = new Date();
d.setDate(d.getDate - 7); // This will subtract 7 days in the date object. 
```

This way of subtracting seven days even works if today is the first day of a month. After the second line of code, the date object will have the date that is 6 days before the end of the previous month.

Also, if you want to know the number of days in the previous month, you can do the following:
```
let today = new Date();
let lastDayOfPreviousMonth = new Date(today.year, today.month, 0);
let numberOfDaysInPreviousMonth = lastDayOfPreviousMonth.getDate();
```

If you wanted to get the number of days in today's month, then you could:
```
let today = new Date();
let lastDayOfMonth = new Date(today.year, today.month+1, 0);
let numberOfDaysMonth = lastDayOfMonth.getDate();
```

**Comment by spectranaut** [comment]
@jongund @mcking65 -- the datepicker works except for this one issue, and it would take a lot to fix it. I don't think it's worth fixing this late in the game. Jon, you might find it interesting to read about how I would have handled the date object and date math, which I detailed in this issue!

**Comment by mcking65** [comment]
I agree, let's fix later -- not before I make the branch cut for the CFC tonight. I'll ask if it is OK to commit a fix to this after the CFC goes out. If so, then we could still include the fix in the publication during the week of July 22 instead of waiting for APG 1.2 at the end of the year.

**Comment by jongund** [comment]
@spectranaut @mcking65 

I have fixed the bug in the date pciker dialog related to aria-selected and it is passing all the regression tests, do you want me to push the changes?

**Comment by jongund** [comment]
@spectranaut 

Valarie, thank you for finding the bug and the suggestions on using the Date object.  There is more that could be done to improve the code to better use features of the Date object and improve readability of the code.  I will look into your suggestions and keep trying to make improvements.  Just going to wait to see if Matt wants to merge the fix I have now or wait until later before making any more changes.

**Comment by spectranaut** [comment]
If the fix is small then perhaps it's worth including it. But I found another but, @jongund -- I don't know how I didn't notice before. Is it fixed after your patch is applied?

To replicate:
1. Load the page.
2. Click the "choose date" button
3. "aria-selected" is on today's date, even though nothing is in the input.

**Comment by spectranaut** [comment]
I added a test to catch both of these bugs. If you check in a fix, also remove ".failing": [test added to PR](https://github.com/w3c/aria-practices/pull/1054/files#diff-c718e7ea20f260bddfac623472e00d85R137)

**Comment by jongund** [comment]
@spectranaut The other bug I saw too and fixed in the patch.  I did a pull and ran the regression tests and it resulted in the following:

```
11 passed
  1 known failure

   datepicker-dialog » dialog-modal/datepicker-dialog.html [data-test-id="gridcell-button-aria-selected"]: aria-selected on selected date
```
is this what I should be getting?

**Comment by spectranaut** [comment]
It looks like it is still failing. Can you remove ".failing" to get the
full error message?

**Comment by spectranaut** [comment]
Oh I just realized I didn't have the correct number of tests planned with "t.plan()" -- there should be 5. I'm adding a commit with that change.

**Comment by jongund** [comment]
@spectranaut Ok did a pull and removed failing again and trying another regression test

**Comment by jongund** [comment]
@spectranaut 

This is the result of the regression test

```
10 passed
  1 failed

  datepicker-dialog » dialog-modal/datepicker-dialog.html [data-test-id="gridcell-button-aria-selected"]: aria-selected on selected date

  C:\inetpub\wwwroot\aria-practices\test\tests\datepicker-dialog.js:145

   144:   await t.context.session.findElement(By.css(ex.buttonSelector)).click(…
   145:   await assertAriaAttributeValue(t, ex.jan12019Button, 'aria-selected',…
   146:

  Rejected promise returned by test. Reason:

  ReferenceError {
    message: 'assertAriaAttributeValue is not defined',
  }



  The .only() modifier is used in some tests. 618 tests were not run
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aria-practices@0.0.0 regression: `ava test/tests "--match" "*datepicker-dialog*"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aria-practices@0.0.0 regression script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jon Gunderson\AppData\Roaming\npm-cache\_logs\2019-07-10T21_59_53_197Z-debug.log
```

**Comment by spectranaut** [comment]
oh! That is my bug in the test. It should be "assertAriaAttributeValues" -- with an s on the end. You can change it locally and see if it passed editing the file now.

**Comment by spectranaut** [comment]
Or rather, `assertAttributeValues`. Fix pushed.

**Comment by jongund** [comment]
@spectranaut @mcking65 

All 11 regression tests are passing now.  So I think it is good to push the changes, let me know.

**Comment by jongund** [comment]
@spectranaut @mcking65 

Created a new branch with the fixes: `issue1072-datepicker-dialog-aria-selected-patch`

[Preview link for aria-selected patch](https://raw.githack.com/w3c/aria-practices/issue1072-datepicker-dialog-aria-selected-patch/examples/dialog-modal/datepicker-dialog.html)

**Comment by mcking65** [comment]
Fixed with commit 8fdc63f. Thank you @jongund and @spectranaut!
