### ISSUE TITLE
Review Modal Dialog Example

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#321]
A [modal dialog example](http://w3c.github.io/aria-practices/examples/dialog-modal/dialog.html) 
developed for issue #103 is ready for review.

#### Reviews requested as of March 15, 2016

- [x] Review by @jnurthen 
- [x] Review by @MichielBijl 
- [x] Review by @shirsha
- [x] Review by @a11ydoer 
- [x] Review by @annabbott

**Comment by terracoda** [comment]
@mcking65, I really like this example, and all the embedded content that explainis the design and design pattern. The example worked very nicely for me with just using the keyboard (in Firefox), and it also worked well in Safari with Voice Over on.

The only visual design issue I noticed (in my quick review) is that while using Voice Over the keyboard focus boarder remains and shows through on the next dialog.

All the examples are very useful!

**Comment by annabbott** [comment]
The modal dialog example page uses entirely different formatting (font, font size, table formatting, etc.) than all other example pages.

**Comment by annabbott** [comment]
Space needed in first bullet under "Verification Result" dialog (id=dialog2):
    Initial focus is set on the first paragraph because the first interactive element is at the bottom, which is out of viewdue to the length of the text. :
Suggested edit:
    Initial focus is set on the first paragraph because the first interactive element is at the bottom, which is out of view due to the length of the text.

**Comment by annabbott** [comment]
I believe it would be incredibly useful to include text in these examples about preserving the user's point of regard when the modal dialog is closed.
Suggested edit:
When a modal dialog is closed (dismissed), set focus back on the control that launched the dialog thereby preserving the user's point of regard.

**Comment by mcking65** [comment]
@annabbot, thanks for the great feedback. I think I have addressed all of it.

**Comment by tatermelon** [comment]
@terracoda, can you please provide a screenshot of the issue you described ("while using Voice Over the keyboard focus boarder remains and shows through on the next dialog")? I haven't noticed any issues that could match that description. Thanks!

**Comment by terracoda** [comment]
@tatermelon, ok. On a closer look, there seems to be some serious focus management issues. I do not rely on VoiceOver, but test with it often. Here are a few screenshots.

Step 1: Opening the first dialog with a reduced window, the forms overflow the dialog.
<img width="640" alt="01-safari-inputs-overflow" src="https://cloud.githubusercontent.com/assets/1902116/24025988/04674e82-0ae4-11e7-8be2-79287830493c.png">

Step 2: VO focus and Keyboard focus are on Verify button. Everything I hear sounds right.
<img width="642" alt="02-safari-fkbfocus-verify-button-06 50 04" src="https://cloud.githubusercontent.com/assets/1902116/24026017/444e0dec-0ae4-11e7-9feb-c598e03aaf76.png">

Step 3: Upon pressing the Verify button, the second dialog opens. VO focus seems to stay on the Verify button.
<img width="640" alt="03-safari-vofocus-still-on-verify-and-kbfocus-on-new-dialog-content" src="https://cloud.githubusercontent.com/assets/1902116/24026060/8e00b156-0ae4-11e7-9a4f-2c95d006a1f2.png">

Step 4: I am able to use Tab key to move keyboard focus to other button in the second dialog, but VO does not follow and does not read out labels.
<img width="641" alt="04-safari-vofocus-and-kbfocus-mismatch" src="https://cloud.githubusercontent.com/assets/1902116/24026196/887d3a96-0ae5-11e7-848b-0e71e0af8b7b.png">

Step 5: Some mismatch continues
<img width="637" alt="05-safari-add-button-showing-through" src="https://cloud.githubusercontent.com/assets/1902116/24026218/97c86228-0ae5-11e7-90ef-9b63f7f21574.png">

Step 6: I use VO hot keys to exit current dialog 2. VO focus moves to dialog 1, but dialog 2 remains open.
<img width="637" alt="06-safari-focus-moves-out-of-current-dialog" src="https://cloud.githubusercontent.com/assets/1902116/24026273/ed725350-0ae5-11e7-84a6-1c9fd8c5cf88.png">

The focus behaviour is confusing to me. And obviously, it is not completely contained within the current dialog. This seems to be a tricky thing to do.

Behaviour in Firefox is different, but I find in general Firefox does work well with VO.

Please note, that I was able to read/listen with VO in Safari to the content in the dialogs, but at some point when focus became mismatched, VO became silent.

I hope this helps.
Using Safari 10.0.03 and Mac OS 10.12.3

**Comment by mcking65** [comment]
@terracoda commented 

> Step 3: Upon pressing the Verify button, the second dialog opens. VO focus seems to stay on the Verify button.

I can verify these problems in Safari but not Chrome. They do not exist on Windows at all.

It seems that the VoiceOver handling of dialogs is not very good in either browser, but it is better with Chrome.

First, to figure out if these behaviors in Safari are script, browser, or VoiceOver bugs, we need to know how it works without VoiceOver. That is something one of you sightees will have to do. We will need to observe what is happening with focus movement, what activeElement returns, and what is in the AX tree.

**Comment by tatermelon** [comment]
@terracoda I will fix the form overflowing, sorry about that! In terms of the VO focus issues, I suspect that is a VoiceOver bug since the focus/focus ring is getting moved and set properly.

**Comment by terracoda** [comment]
@tatermelon, I think it is also a VO bug.

There is one more obvious issue, the user can navigate out of the current dialog without actually closing it. For me this happens in both Safari and Firefox. This seems to be a common issue for many publicly available examples of dialogs.

I'll check back for updates before doing more testing.

**Comment by shirsha** [comment]
It is working fine with JAWS 18 in IE11. 
Screen reader is not reading the  "Add Delivery Address" heading when model dialog box is opened. It reading the street address label as soon as dialog box is opened. Even when the user tabs to next input field it still reads Street address label. 
When user selects enter to activate Close button( focus is on close button), nothing happens.
When user selects the "Link to help" link, screen reader reads the heading and content inside it but again on selecting close button nothing happens. When user tabs now the focus is taken out of the model dialog box.
Same thing happens when user selects "accepting an alternative form" and select close button.
Please see the attached screen shots

[Model dialog box-321.docx](https://github.com/w3c/aria-practices/files/855282/Model.dialog.box-321.docx)

**Comment by a11ydoer** [comment]
"close" button on dialog4(accessed by "accepting an alternative form" button) does not have a focus and can not activate it.

**Comment by mcking65** [comment]
@terracoda commented:

> There is one more obvious issue, the user can navigate out of the current dialog without actually closing it. 
> For me this happens in both Safari and Firefox.
> This seems to be a common issue for many publicly available examples of dialogs.

Do you mean you can move keyboard focus outside the dialog? I can not reproduce this. Please provide steps for reproduction.

Or, do you mean with a screen reader reading cursor? If so, this is a screen reader bug and/or feature, depending on which screen reader and how you are using it.

Basically, screen reader users should have the same kind of capabilities as all other users. So, if other users can "see" what is outside the dialog, then screen reader users should at least have some way of doing that. By default, though, screen reader reading should be restricted to the dialog boundaries when focus is inside the dialog. 

In general, this pattern is not yet very well supported by screen readers. I think that many screen reader users get by pretty well, but there is a lot, a lot of room for improvement.

**Comment by mcking65** [comment]
@a11ydoer commented:

> "close" button on dialog4(accessed by "accepting an alternative form" button) does not have a focus and can not activate it.

Jemma, I cannot reproduce this in Firefox or Chrome. Here are the steps I followed:

1. Focus and activate "Add Delivery Address" button.
2. Tab to "Verify Address" button and activate with space.
3. Tab to "accepting an alternative form" button and press enter or space.

At this point, the "Close" button is focused. I can activate it.

Are you saying that something causes the focus indicator to disappear after step 3?

**Comment by a11ydoer** [comment]
@mcking65 

After step 3, there is a focus on "close" button for the paragraph "End of the Road! You activated a fake link or button that goes nowhere! The link or button is present for demonstration purposes only." This is dialog4.  

However, I cannot close the dialog4 with either enter or space key. Actually, pressing either space or enter key with focus on "close" button in dialog4 moves back the focus to " accepting an alternative form", which is in dialog2.  I guess this may be the intended design for demo but it is confusing to me in that "close" button in dialog4 does not close dialog4 and rather move the focus back to " accepting an alternative form" in dialog2.   Does this make sense?

**Comment by accdc** [comment]
Hi,
There are issues with the modal dialog. When the first and second modal open, focus is being set to static non-interactive elements, the first being a span tag and the second being a p tag, which should not be the case. No non-interactive static elements should be focusable or in the tab order.

Also, when the Add button is activated a scripting error occurs, as is true when the Close button in the third dialog is activated, discovered in IE11 which prevents the dialogs from acting properly such as closing in the third dialog. E.G The third dialog cannot be closed when the Close button is activated.

**Comment by mcking65** [comment]
@accdc commented:

> When the first and second modal open, focus is being set to static non-interactive elements, 
> the first being a span tag and the second being a p tag, which should not be the case. 

Bryan, this should not happen in dialog 1. It only happens in dialog 1 in IE, not any other browser. I'll look into it.

Focusing the first paragraph in dialog 2 is intentional due to the content size. Please read the dialog content, the accessibility features, and the pattern and the notes. This is a case where a static element is, and needs to be, focusable. However, I do pklan to change it from tabindex of 0 to -1.

> Also, when the Add button is activated a scripting error occurs, as is true when the Close button in the third dialog is activated, discovered in IE11,
> which prevents the dialogs from acting properly such as closing in the third dialog. E.G The third dialog cannot be closed when the Close button is activated.

Hmm, again this is another IE oddity. It works perfectly in Chrome, and Firefox on both Win and Mac as well as Safari. We'll look into it. Thanks.

**Comment by mcking65** [comment]
@accdc, please retest. I think all the IE issues you raised have been addressed.

**Comment by accdc** [comment]
Hi,
Issues still remain.

I looked at the JS and the way that the first and last focusable child elements are detected does not work reliably in IE, even if they do in FF. To make this work reliably, it the logic needs to check if the first/last focusable element is 'focusable' by checking the following logic in this order:

1. Is the element a rendered form field (input, select, or button element )or link (a tag that includes an href attribute), then set focus to it.
2. Or if the element is a static element does it include tabindex="-1", if yes then set focus to it.
3. Otherwise if 1 and 2 are false, move to the next element.

This will make it cross browser compatible.

Also, in the third dialog, the following element should not include tabindex="0":

<p tabindex="0">This is just a demonstration. If it were a real application, it would
          provide a message telling whether the entered address is valid.</p>

Ideally the first link should receive focus, but if the desire is to set focus to this text instead then tabindex="-1" needs to be used instead.

**Comment by tatermelon** [comment]
@accdc Are you sure you are on the latest version? We just updated the logic a few hours ago to check if something is focusable in that order. We had also updated the focused text to use tabindex="-1" instead of 0.

**Comment by mcking65** [comment]
@accdc, Just before I asked you to retest, we pushed commits 7862b13 and cccb08b that have those changes. I checked travis and the build to gh-pages was successful. It is working for me in IE when I run from gh-pages.

Maybe refresh your cache?

**Comment by jnurthen** [comment]
trying on iOS I get the background scrolling with a swipe up/down at a different rate to the foreground. This gives a really annoying parallax effect.

**Comment by a11ydoer** [comment]
Also different dialog sizes/styling in the example would help to understand intuitively four different dialog focus management/work flow used in the example.

**Comment by jnurthen** [comment]
Not seeing the behaviour I stated before but am seeing a different strange behaviour on iphone. Steps to reproduce are as follows:

- on iPhone (ios 10.3.1) open the modal dialog pattern in safari (note do not have VO running)
- Click the Add Delivery Address button
- Click the Verify Address button

Note I cannot scroll all the way to the bottom in order to press the buttons. It bounces back and I cannot activate them.

**Comment by mcking65** [comment]
Friendly reminder to @jnurthen, @annabbott, @shirsha, please have one last look with latest revisions in place and comment on whether or not you think we are ready to close this review.

**Comment by a11ydoer** [comment]
@mcking65 
This example template looks different from other example template because of CSS attributes, width 100% and height 100% in newly added <div id="base_window_layer">. This modification was intended to remedy the problem in mobile devices and double scroll issue as far as I remember the discussion at the meeting. I was wondering whether we need to note this example template difference somewhere so that readers do not think this is not an error. Any thought?

**Comment by shirsha** [comment]
JAWS 18 in IE11, Screen reading the street address label even when the user tabs to next input field it still reads Street address label.

Focus is not visible clearly. .

Tie special instructions to the input field using "aria-describedby" so that screen reader user can hear them when user tabs into that input field.

**Comment by shirsha** [comment]
Focus is not visible clearly on the buttons

JAWS18 in IE11:

- Screen reader is not reading the "Add Delivery Address" heading when model dialog box is opened.
- It reading the street address label as soon as dialog box is opened. Even when the user tabs to next input field it still reads Street address label.

- Add role-dialog before the content start so that it put screen reader user in virtual mode

**Comment by shirsha** [comment]
Tie the additional information after the "Special instructions"  label  to the input field by using "Aria-describedby " so that screen reader user can hear the additional example text when they tab to the Special instructions input field

**Comment by annabbott** [comment]
@mcking65 - please notify me when work is completed on this example and needs further review - Thanks!

**Comment by DavidMacDonald** [comment]
Yeah VoiceOver mangles it as it does almost all dialogues.

**Comment by smartm0use** [comment]
I'm trying to reproduce the [same example](http://w3c.github.io/aria-practices/examples/dialog-modal/dialog.html) on Plunker, but it doesn't work: https://plnkr.co/edit/RXJciG

Can you tell me what's wrong with my sample?

**Comment by mcking65** [comment]
All feedback has now been addressed. Thank you everyone for all the excellent feedback and testing. Closing!
