### ISSUE TITLE
Navigation Menubar Example: Parents of Submenus Do not Correctly Update aria-expanded

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#472]
Parents of second level submenus in the 
[navigation menubar example](http://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html) 
do not correctly update the value of aria-expanded.
For example, when the "Facts" submenu within the "About" menu is expanded, the parent "Facts" menuitem still has aria-expanded set to false.

Reported by @devarshipant in 
[issue 410](https://github.com/w3c/aria-practices/issues/410#issuecomment-335468509).

**Comment by jongund** [comment]
I have fixed the bug and it is part of pull request 448:
https://github.com/w3c/aria-practices/pull/448

**Comment by mcking65** [comment]
@jongund, did you see my [comment in pull 448](https://github.com/w3c/aria-practices/pull/448#issuecomment-335687244)?

This issue still does not seem to be resolved in Firefox ... at least not when I inspect using JAWS.

**Comment by mcking65** [comment]
Fixed with pull #487, commit c067389, and thanks to @jongund!
