### ISSUE TITLE
menubar example bug: missing role="none" on some <li>

### ISSUE THREAD

**Issue by mfairchild365** [w3c/aria-practices#930]
The menubar-1.html example says that the `<li>` elements under the `role="menubar"` should have `role="none"`. The example states this under the "Role, Property, State, and Tabindex Attributes" table.

However, the [actual example does not include `role="none"` on the `<li>` elements](https://github.com/w3c/aria-practices/blob/master/examples/menubar/menubar-1/menubar-1.html#L53).

I think this might be causing NVDA 2018.3.2 + Firefox 62 to announce each menuitem has “1 of 1” instead of "1 of 3".

I'm happy to submit a PR to fix this if you want, but I thought I'd confirm before I create a PR.

**Comment by jnurthen** [comment]
I believe this is already fixed. Can you verify in the master branch?

**Comment by carmacleod** [comment]
It is still missing on the live page: http://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html
(Does the github.io page get created immediately from master, or do I have to bust the cache or something?)

**Comment by carmacleod** [comment]
The menubar-2 (Editor Menubar) example does have `<li role="none">`.

**Comment by mfairchild365** [comment]
Great! I'll submit a PR tomorrow (time allowing).

**Comment by mfairchild365** [comment]
Okay, a quick clarifying question here. Are the `<li>` elements without `role="none"` valid according the ARIA spec here? It feels wrong to me, and it creates AT bugs, so I'll submit a PR anyway. But I want to better understand this.

In the example, `role=”menubar”` will override the `<ul>` role. The `<li>` will still have the `listitem` role, but is now orphaned because a `listitem` requires a parent of `group` or `list`. The `menubar` is neither of those.

… or is it? If you follow the inheritance of `menubar`, it has a superClass role of `group`. I haven’t been able to find anything normative that describes how a superClass role affects the “Required Context Role”. Do I understand correctly that the RDF spec states that `role:scope` properties are inherited from `rdfs:subClassOf`, and thus a `<li>` without a `role="none"` is technically valid?
